name: Hprofile Action
on: workflow_dispatch
jobs: 
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: maven test
        run: mvn test
      - name: Checkstyle
        run: mvn checkstyle:checkstyle
      - name: Checkstyle  
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          architecture: 'x64'

        
